### ISSUE TITLE
Allow form data to be attached to each task when uploading

### ISSUE THREAD

**Issue by luluseventhbeam** [781flyingdutchman/background_downloader#28]
I have a use case, where I need to be able to add form data to the multipart/form-data upload request. 

We have a lot of images that will be uploaded and each has associated data that needs to be sent with it.

It would be great if the UploadTask object could have a Map<String, String> property for adding this.

**Comment by 781flyingdutchman** [comment]
Hi @luluseventhbeam, I've implemented this on the `upload_fields` branch and before I publish it, I was wondering if you could test the functionality and confirm it works as you expect it to?  To use the unpublished version with this feature, change your pubspec.yaml entry to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: upload_fields
```
To add fields to your `UploadTask`, simply set `fields` to a `Map<Sgtring, String>` with name/value pairs. This only works for multi-part uploads, not for binary uploads (where you set `post` to 'binary') but that doesn't seem to be your use case.
