### ISSUE TITLE
"Complete" notification is shown before last "Running" notification

### ISSUE THREAD

**Issue by philitell** [781flyingdutchman/background_downloader#475]
**Describe the bug**
I'm using group-notifications to show running- and complete-state notifications. When i'm downloading 10 small files **sometimes** the last notification that is shown on android is "9 of 10 files". The notification with the complete-message is shown a fraction of a second before that and is then replaced by the next notification with the content "9 of 10 files". Is there something i can do about that?

**To Reproduce**
Unfortionally hard to reproduce because it seems to be a timing issue.

**Expected behavior**
The notification with the complete-messsage should always be the last notification visible.

**Logs**
If possible, include logs that capture the issue:
```
logs
```

**Code**
My config:
```
      final FileDownloader _fileDownloader;
       ....
      await _fileDownloader.ready;
      final configResult = await _fileDownloader.configure(
        globalConfig: [
          (Config.requestTimeout, const Duration(seconds: 100)),
          (Config.checkAvailableSpace, 500),
        ],
        androidConfig: [
          (Config.useCacheDir, Config.whenAble),
        ],
        iOSConfig: [
          (Config.localize, {"Cancel": S.current.stopIt}),
        ],
      );
      repositoryLogger.info("FileDownloader configuration result:"
          "\n $configResult");

      // Register an event listener to process status and progress updates
      ....

      repositoryLogger.info("Start persistent task tracking");
      await _fileDownloader.trackTasks();

```

Here here notification configuration for android:
```
 _fileDownloader.configureNotificationForGroup(
        groupIdentifier,
        running: const TaskNotification("{numFinished} von {numTotal}", "Fortschritt: {progress}"),
        complete: const TaskNotification("Abgeschlossen", "{numTotal} Dateien heruntergeladen"),
        error: const TaskNotification("Fehler", "{numFailed}/{numTotal} fehlgeschlagen"),
        progressBar: true,
        groupNotificationId: "notification_$groupIdentifier",
      );
```

**Additional context**
 - i'm using downloadTasks which generate only Status updates

**Comment by 781flyingdutchman** [comment]
Let me look into this - I assume this is on Android? Can you confirm the version of the downloader you are using?

**Comment by philitell** [comment]
Yes - on Android.
`background_downloader: ^9.1.0`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.1, on Ubuntu 24.04.2 LTS
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.96.3)
[✓] Network resources

```

**Comment by 781flyingdutchman** [comment]
Tried a different approach that I think may work, and would like your help testing it. Can you change your pubspec.yaml entry to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: group_notifications
```

and see if this the issue still occurs (or if another issue occurs - especially concerned about deadlocks that prevent notification updates from happening)?  Thanks!

**Comment by philitell** [comment]
I've done some testing: i was still able to reproduce this issue for both usecases:
 - when downloading multiple files in a single group
 - when downloading multiple files in multiple groups

pubspec.lock:
```
 background_downloader:
    dependency: "direct main"
    description:
      path: "."
      ref: group_notifications
      resolved-ref: dcdf36a93552d97cc595a87d4b405fefed3e4c2a
      url: "https://github.com/781flyingdutchman/background_downloader.git"
    source: git
    version: "9.1.1"
```

pubspec.yaml
```
  background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: group_notifications
```

<img src="https://github.com/user-attachments/assets/7c964f87-6a58-44a1-baf8-f5658924e856" width=200>
